### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by VicMahoney** [zzh-tech/InterpAny-Clearer#1]
Hello! Tell me, is there any complete installation instructions for a beginner?
To have a complete set of programs for working with video.
And you can find out how long the video is interpolated and with which video cards.

**Comment by zzh-tech** [comment]
> Hello! Tell me, is there any complete installation instructions for a beginner?
We will release a Docker Image soon.

**Comment by zzh-tech** [comment]
Docker instructions are uploaded.

**Comment by VicMahoney** [comment]
The installation turned out to be too complicated for me, I’m tired of installing such things, all the time some elements do not work and give errors
sorry to bother you

**Comment by zzh-tech** [comment]
Yeah, totally understood :-)
Well, at least you can try the interactive demo:
http://ai4sports.opengvlab.com/interpany-clearer/

**Comment by VicMahoney** [comment]
@zzh-tech The question is, can I even do video interpolation with this tool? Now I use flowframes, as I understand it, your model is clearer? Video size is 1080 or more, films and TV series lasting 30 minutes or more - processing takes 20 minutes +(rtx 3060 ti). How fast is your model?

**Comment by zzh-tech** [comment]
> The question is, can I even do video interpolation with this tool?  
No, the current webapp tool can only support interpolation for two frames.
We do offer an API for video inference, but it requires setting up the environment first. 

> Now I use flowframes, as I understand it, your model is clearer?
Yes, the goal of this work is to enhance state-of-the-art video frame interpolation algorithms, making them clearer and editable.

> How fast is your model?
Our method optimizes existing models. The speed depends on how fast the model itself is.  
For instance, if you use [D] RIFE-pro, its speed is the same as the original RIFE (https://github.com/megvii-research/ECCV2022-RIFE). [D,R] RIFE-pro with 2 iterations would be twice as slow but better.

We are considering developing video frame interpolation tools for non-technical people, stay tuned.

**Comment by VicMahoney** [comment]
@zzh-tech "We do offer an API for video inference, but it requires setting up the environment first." - I meant that if I install the entire application package via Docker (as in your example command for interpolation, where i need to select a model, a folder for video output), will I be able to interpolate the video? Through the web interface I realized that there are only two frame can be done

**Comment by zzh-tech** [comment]
> will I be able to interpolate the video? 

Sure.

**Comment by zzh-tech** [comment]
> We are considering developing video frame interpolation tools for non-technical people, stay tuned.

Done
https://ai4sports.opengvlab.com/interpany-clearer/
