### ISSUE TITLE
installation problem 

### ISSUE THREAD

**Issue by VicMahoney** [zzh-tech/InterpAny-Clearer#14]
Hello again!
Help the teapot install your software finally!
Now i trying to use Docker and i cant run it ...
1) where to get "nvidia-container-toolkit >= 1.3"? what is it - like driver or what?
2) i opened a docker and where do i need to put in this line "docker build -t interpany:v0 -f docker/Dockerfile ." ?maybe there is some fast explanation guide?

**Comment by Wei-ucas** [comment]
For linux, 
1. please refer to [nvidia doc](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) to install nvidia-container-toolkit. 
2. You can run this command in the terminal under the project path.

For windows (we haven't tried it, but it should work)
1. GPU support in Docker Desktop is only available on Windows with the WSL2 backend, please refer to https://docs.docker.com/desktop/gpu/ to make sure your docker can run with gpu.
2. You can run this command in the windows cmd under the project path. 

There are lots of documents or blogs about how to use docker, you can google it  and have a try.

Feel free to discuss here if you have more questions.

**Comment by VicMahoney** [comment]
where if the 

> For linux,
> 
> 1. please refer to [nvidia doc](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) to install nvidia-container-toolkit.
> 2. You can run this command in the terminal under the project path.
> 
> For windows (we haven't tried it, but it should work)
> 
> 1. GPU support in Docker Desktop is only available on Windows with the WSL2 backend, please refer to https://docs.docker.com/desktop/gpu/ to make sure your docker can run with gpu.
> 2. You can run this command in the windows cmd under the project path.
> 
> There are lots of documents or blogs about how to use docker, you can google it and have a try.
> 
> Feel free to discuss here if you have more questions.

where is the project path?
![x1](https://github.com/zzh-tech/InterpAny-Clearer/assets/149694958/93060573-3a4e-48b6-9734-034650a6b47f)

**Comment by VicMahoney** [comment]
Do i need to install anaconda and Environment if i try to use docker?

**Comment by VicMahoney** [comment]
i almost did it 
![x2](https://github.com/zzh-tech/InterpAny-Clearer/assets/149694958/d753023b-c829-4f6d-bbe6-89956a69efb0)

**Comment by VicMahoney** [comment]
That's it, I gave up on Docker
It seems like I made a build through anaconda

**Comment by VicMahoney** [comment]
now i cant install webapp
how its looks like in use?
i mean is it faster that powershell cmd to set up configuration for videos to interpolate?

**Comment by VicMahoney** [comment]
again problem with interpolation 
numpy.core._exceptions.MemoryError: Unable to allocate 23.9 MiB for an array with shape (2176, 3840, 3) and data type uint8

i got 16 video memory, 32 gm ram, big ssd
i need gui ready build, cant install this s..t manually
will it ever be made for any purpose?

**Comment by Wei-ucas** [comment]
> where is the project path? ![x1](https://private-user-images.githubusercontent.com/149694958/331871172-93060573-3a4e-48b6-9734-034650a6b47f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTQwOTAsIm5iZiI6MTcxNjE5Mzc5MCwicGF0aCI6Ii8xNDk2OTQ5NTgvMzMxODcxMTcyLTkzMDYwNTczLTNhNGUtNDhiNi05NzM0LTAzNDY1MGE2YjQ3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwODI5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGI4MDE0MmE0MjAyZGZlYzRjN2U1NDU3ZTM2NTk4OGY1MmJkNTIxZmZjY2U5NDllZDdmYzA3ZmYyZjkwZGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l3lcqzjpSJ93fmrAyqlNQfLYz83EWgMbjsER7YsTBOQ)

The project path is the folder where you put this InterAny-Clearer folder, for example:
```shell
git clone https://github.com/zzh-tech/InterpAny-Clearer.git
cd InterpAny-Clearer 
docker build -t interpany:v0 -f docker/Dockerfile .
```

No need to install Anaconda if you use docker,  the environment will be ready if you run the container with docker.

You can follow the https://github.com/zzh-tech/InterpAny-Clearer/blob/main/webapp/backend/README.md and https://github.com/zzh-tech/InterpAny-Clearer/blob/main/webapp/webapp/README.md to run the webapp.  Runing command in shell maybe more convenient as the webapp installation has some difficulties.

We have no plans to develop a GUI app.
