### ISSUE TITLE
Can you provide the small model of T-EMA?

### ISSUE THREAD

**Issue by ustczhouyu** [zzh-tech/InterpAny-Clearer#15]
Hi, it is a good job and I want to use the EMA to do some experiments, can you provide the small model of T-EMA?Thank you~

**Comment by zzh-tech** [comment]
Did you mean EMA-VFI?
https://github.com/MCG-NJU/EMA-VFI

**Comment by ustczhouyu** [comment]
> Did you mean EMA-VFI? https://github.com/MCG-NJU/EMA-VFI

Yes, I would appreciate it if you could provide

**Comment by zzh-tech** [comment]
Unfortunately, we only have normal-sized EMA-VFI checkpoints.
https://drive.google.com/drive/folders/17p-hsSnkp40ck6tyt8x4V8erIVChGOeO?usp=sharing
