### ISSUE TITLE
Inference torch array size mismatch

### ISSUE THREAD

**Issue by Kirstihly** [zzh-tech/InterpAny-Clearer#16]
To whom it may concern,

Hello! I'm very interested in the inference demo and would like to try on my own image frames. But when I try RIFE models with `--model RIFE --variant DR`, they will all point to this error: `RuntimeError: Sizes of tensors must match except in dimension X. ....`

I double-checked the code and looks like the `warped_img1`, `warped_img2`, `flow`, `mask` sizes changed after each iteration in file `./models/DI-RIFE/model/IFNet_sdi_recur.py`. I'm wondering if they can be directly cropped or padded with zero to ensure the size consistency? Thank you!

**Comment by zzh-tech** [comment]
Hi, I forget to pad the input images for RIFE model.
Please refer to the inference code of other models, like below:
https://github.com/zzh-tech/InterpAny-Clearer/blob/6dfd40857008c75b3e784692ac67a9f646eadeab/models/DI-EMA-VFI/inference_img_plus_sdi_recur.py#L23

I will fix this later.

**Comment by zzh-tech** [comment]
Fixed.
