### ISSUE TITLE
为什么生成distance map时需要进行下采样？

### ISSUE THREAD

**Issue by cslvjt** [zzh-tech/InterpAny-Clearer#18]
作者你好，感谢你做出的优秀的工作，关于计算distance map的代码部分，请问为什么需要下采样？

**Comment by cslvjt** [comment]
![image](https://github.com/user-attachments/assets/248d4487-3fb2-42db-ac98-f6e7e975c130)

**Comment by zzh-tech** [comment]
这个当时是考虑到存储空间有限，所以下采样了。
如果选择在训练过程中直接利用optical flow estimator去在线计算map进行训练，完全可以采用全分辨率。
关于这方面我没有系统地进行实验，但我有一个猜想：
或许全分辨率的提升并不会太大，因为本身optical flow也有不准确的问题，下采样的量化过程反而减少了错误的影响。

**Comment by cslvjt** [comment]
好的，谢谢回复
