### ISSUE TITLE
Running the rife model, it always fills up the memory and gets killed

### ISSUE THREAD

**Issue by hola5156** [zzh-tech/InterpAny-Clearer#20]
Even with 120G memory, how to solve

**Comment by zzh-tech** [comment]
Haven't had a similar problem.  
Are you entering two images or a video and how big are they?

**Comment by hola5156** [comment]
Videos with dynamic frame rates and dynamic bit rates from acfun.com . typically range in size from 100MB to 300MB. I've tested interpolation on domestic cloud GPUs, 
Videos with fixed frame rates and dynamic bit rates also deplete memory during testing.

**Comment by zzh-tech** [comment]
Splitting the video into multiple short videos, interpolating them and then merging them together is one solution. Alternatively, you can modify the video inference code (e.g., “models/DI-RIFE/inference_video_plus_sdi.py”), which now does this by extracting all frames and interpolating them.
