### ISSUE TITLE
Set frame rate of output video?

### ISSUE THREAD

**Issue by SoftologyPro** [zzh-tech/InterpAny-Clearer#4]
For example, if I have a source video that goes for 5 seconds at 10 fps.  50 frames total.
I want to smooth it to 40 fps (2 iterations in InterpAny-Clearer). ~200 frames total.
But the resulting movie is still 10 fps so rather than being the same playback length and smoother, it is 4 times as long and slow motion.

Is there a way to tell InterpAny the fps of the output movie?
Other interpolators keep the same playback length and increase the fps to compensate for the extra frames.

**Comment by zzh-tech** [comment]
> Is there a way to tell InterpAny the fps of the output movie?

Sure, taking [D,R] RIFE-pro as an example, you can find the specific video inference API like this:
https://github.com/zzh-tech/InterpAny-Clearer/blob/624551926afed92917fcb630f1a1d4d036e2377c/inference_video.py#L66C9-L66C9

And then modify the fps of the saved video, which is the same as the input video by default:
https://github.com/zzh-tech/InterpAny-Clearer/blob/624551926afed92917fcb630f1a1d4d036e2377c/models/DI-RIFE/inference_video_plus_sdi_recur.py#L127C1-L128C1

Later I will add a parameter to control the fps of the interpolated video, stay tuned ;-)

**Comment by zzh-tech** [comment]
> Later I will add a parameter to control the fps of the interpolated video, stay tuned ;-)

Done
