### ISSUE TITLE
Model zips damaged?

### ISSUE THREAD

**Issue by SoftologyPro** [zzh-tech/InterpAny-Clearer#5]
Click Download all here
https://drive.google.com/drive/folders/11MY60fpDk5oAlGasQRZ3ss3xVdrOBIiE
It creates the zips and downloads 5 files, but the third is corrupted, it shows as
events.out.tfevents.1692391377.zzhong-imaging.39609-002-003.0
and when renamed to zip it will not extract.
Can you fix it?  I want to try the other models and variants.
Maybe rezip and upload as a single zip file?

**Comment by hack-mans** [comment]
@SoftologyPro Yeah I just had to download some of the files individually, the events files are messing with the zipping for some reason

**Comment by zzh-tech** [comment]
Try this:
https://drive.google.com/file/d/14GJSqsX4H5EcQjd-tLb5CM_jzD-577bl/view?usp=sharing

**Comment by SoftologyPro** [comment]
Seems way too small?  I did manage to download all the files in the end with some manual downloads and downloading subfolders as needed, but when I zip all that up it comes to around 10 GB in size for all the models.

**Comment by zzh-tech** [comment]
I removed unnecessary tensorboard logs.

**Comment by SoftologyPro** [comment]
OK, thanks.  I can confirm the zip works and all combos of model and variation work.
