### ISSUE TITLE
Regarding the accuracy in paper

### ISSUE THREAD

**Issue by starrysky-ashin** [zzh-tech/InterpAny-Clearer#6]
Hi, I read your excellent paper "Clearer Frames, Anytime: Resolving Velocity Ambiguity in Video Frame Interpolation".

I am a little curious abou the accuracy of [D] in this paper. In this test setting, do we need to run the RAFT model to obtain the optical flow from input frames to the target frame? If so, this setting has leveraged the information of target frame, which might be unfair for comparison.

**Comment by zzh-tech** [comment]
Thank you for your interests.

>  In this test setting, do we need to run the RAFT model to obtain the optical flow from input frames to the target frame? If so, this setting has leveraged the information of target frame, which might be unfair for comparison.

We have explained this in our paper:

The models $[D]$ and $[D,R]$ in the upper half of Table 1 utilize ground-truth distance guidance, which is not available at inference in practice. **The goal here is just to show the achievable upper-bound performance.** In realistic scenarios where the precise distance map is inaccessible at inference, one could resort to a uniform map akin to time indexing. The bottom segment of Table 1 shows the performance of the enhanced models $[D]$ and $[D,R]$, utilizing identical inputs as model $[T]$, *i.e.*, $[D]_u$ and $[D,R]_u$. Given the misalignment between predicted frames using a uniform distance map and the ground-truth, the enhanced models do not outperform the base model on pixel-centric metrics, but significantly outperforms the base model on perceptual metrics. We argue that in most applications, the goal of VFI is not to predict pixel-wise aligned frames, but to generate plausible frames with high perceptual quality.
