### ISSUE TITLE
Memory error and performance issue

### ISSUE THREAD

**Issue by VicMahoney** [zzh-tech/InterpAny-Clearer#7]
@zzh-tech 
Hello again!
I have rtx 3060 ti 8gb.
When I tried to do a test of a 10 second 4K video, I got this error:
numpy.core._exceptions.MemoryError: Unable to allocate 23.9 MiB for an array with shape (2176, 3840, 3) and data type uint8

Also a minute of full hd video took almost 30 minutes on default settings (demo with model RIFE --variant DR) and got the same memory error . 
numpy.core._exceptions.MemoryError: Unable to allocate 2.70 MiB for an array with shape (736, 1280, 3) and data type uint8
And in general, the question is, how many models are there to try? How to change models on the command line?

After all this I got an error
Traceback (most recent call last):
  File "A:\InterpAny\models\DI-RIFE\inference_video_plus_sdi_recur.py", line 10, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Upd
i understood how to solve the last problem - with every new start terminal,we need to run "conda activate InterpAny" and there is no error in 'cv2'

**Comment by zzh-tech** [comment]
Using [D] instead of [D,R] can save the required memory.

> what minimum memory does the program need?

It depends on the model. Using [D] should cost the same amount of memory as each original model. However, we did not count the memory cost for each model.
