### ISSUE TITLE
Are PT or PTH files available to be used with conventional model loaders like in ComfyUI?

### ISSUE THREAD

**Issue by oliverban** [zzh-tech/InterpAny-Clearer#9]
As the title says. The PKL files could theoretically be converted to PT or PTH and used in other workflows such as ComfyUI if a node could be created to interface with the cmd-line.

**Comment by zzh-tech** [comment]
Hi, thank you for your interests.
Unfortunately, I am not familiar with ComfyUI.
In fact, the suffix is set arbitrarily, either 'pkl' or 'pt'. Information that might be useful to you is that all checkpoints are saved in the standard way in pytorch, for example:
https://github.com/zzh-tech/InterpAny-Clearer/blob/7ba1ba8ff940391b62c6448b4461417ef82b3975/models/DI-RIFE/model/RIFE_sdi_recur.py#L71C13-L77C70

**Comment by oliverban** [comment]
> Hi, thank you for your interests. Unfortunately, I am not familiar with ComfyUI. In fact, the suffix is set arbitrarily, either 'pkl' or 'pt'. Information that might be useful to you is that all checkpoints are saved in the standard way in pytorch, for example: https://github.com/zzh-tech/InterpAny-Clearer/blob/7ba1ba8ff940391b62c6448b4461417ef82b3975/models/DI-RIFE/model/RIFE_sdi_recur.py#L71C13-L77C70

Interesting, yes thanks you for that! It means I could potentially put the models in there if nothing "special" is needed, I will experiment! Thanks again!
